#!/bin/bash

source config/env

# 
# Shortcuts
# 

case $1 in
	'' )
		;;
	'logs' )
		heroku logs --tail --app shadow;;
	'm' )
		mate .;;
	'processing' )
		heroku logs --tail --app shadow -p worker;;
	'production' ) 
		git remote rm heroku
		git remote add heroku "git@heroku.me:shadow.git";;
	'rake' ) 
		rake $2;;
  's' )
		bundle exec unicorn;;
	'setup' )
		cp config/env ~/.dotfiles/site-env;;
	'staging' )
		git remote rm heroku
		git remote add heroku "git@heroku.me:shadow-staging.git";;
  'styled' )
		export STYLESHEET_DEVELOPMENT=true
		bundle exec unicorn;;	
  'test' )
		export RAILS_ENV='test'
		if [[ $2 == 'features' ]]; then export AUTOFEATURE='true'; fi
		bundle exec autotest;;
  * )
		rails "$@";;
esac
