#!/bin/bash

source config/env

# 
# Shortcuts
# 

case $1 in
	'' )
		;;
	'deploy' )
		git checkout master && git merge staging && git push && git checkout development;;
	'logs' )
		heroku logs --tail --app shadow;;
	'm' )
		mate .;;
	'processing' )
		heroku logs --tail --app shadow -p worker;;
	'production' ) 
		git config --unset-all heroku.remote
		git config --add heroku.remote production;;
	'rake' ) 
		rake $2;;
  's' )
		bundle exec unicorn;;
	'setup' )
		cp config/env ~/.dotfiles/site-env;;
	'stage' ) 
		git checkout staging && git merge development && git push && git checkout development;;
	'staging' )
		git config --unset-all heroku.remote
		git config --add heroku.remote staging;;
  'styled' )
		export STYLESHEET_DEVELOPMENT=true
		bundle exec unicorn;;	
  'test' )
		export RAILS_ENV='test'
		if [[ $2 == 'features' ]]; then export AUTOFEATURE='true'; fi
		bundle exec autotest;;
  * )
		rails "$@";;
esac
